FROM gitlab-master.nvidia.com/dl/dgx/pytorch:21.10-py3-devel
# TODO delete this and revert to nemo container after release 1.5
RUN apt update && rm -rf /var/lib/apt/lists/*

# Ensure apt-get won't prompt for selecting options
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    libsndfile1 sox \
    python-setuptools swig \
    python-dev ffmpeg && \
    rm -rf /var/lib/apt/lists/*

RUN pip install pytorch-lightning==1.5.0rc0 && \
	sed -i "s/from pytorch_lightning.callbacks.quantization import QuantizationAwareTraining/try:\\n\\tfrom pytorch_lightning.callbacks.quantization import QuantizationAwareTraining\\nexcept:\\n\\tpass/g" /opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py

# Commit from main
ARG NEMO_BASE_HOME=/workspace/nemo_base
RUN git clone https://github.com/NVIDIA/NeMo.git ${NEMO_BASE_HOME} && \
    cd ${NEMO_BASE_HOME} && \
	git checkout 80fd43106624ecff8a9b38db7536e9a6f2e33896 && \ 
	sh reinstall.sh

RUN pip install wandb==0.10.21