# Copyright (c) 2022, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: replace with nemo 1.8 released container
# FROM nvcr.io/nvidia/nemo:22.01
# FROM gitlab-master.nvidia.com/mlivne/nemo_containers:nemo-r1.8.0
FROM gitlab-master.nvidia.com/sandeepsub/nemo_containers:nemo-190-2204-apex
ARG GITHUB_ACCESS_TOKEN
ARG GITHUB_BRANCH
ARG NEMO_CHEM_HOME=/workspace/nemo_chem
ARG CONDA_ENV=base

ENV GITHUB_BRANCH=${GITHUB_BRANCH}

# Activating base environment
RUN echo "source activate base" > /etc/bash.bashrc
ENV TERM=xterm

## Installing tmux and vim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
    python-setuptools python-dev swig \
    wget git unzip tmux vim && \
    rm -rf /var/lib/apt/lists/*

# TODO: check if required
## Upgrade NeMo
# RUN pip install nemo_toolkit[all]==1.7.2

## Environment setup --  multithreaded dataloading very sensitive to libboost version. Do not change w/o testing.
COPY conda/env.yml /tmp/env.yml
RUN conda env update --name base -f /tmp/env.yml && conda clean -afy

## PySMILES
RUN git clone https://github.com/MolecularAI/pysmilesutils.git --branch master /opt/pysmilesutils \
    && cd /opt/pysmilesutils; pip install .

RUN pip install --upgrade numpy wandb

## NeMo_MegaMolBART
# TODO update path to public one and remove access token and branch
RUN git clone https://${GITHUB_ACCESS_TOKEN}@github.com/clara-parabricks/NeMo_MegaMolBART.git ${NEMO_CHEM_HOME} \
    && cd ${NEMO_CHEM_HOME} \
    && git checkout ${GITHUB_BRANCH}

RUN cd ${NEMO_CHEM_HOME} && conda run -n ${CONDA_ENV} pip install -e .

# Recompile Megatron helpers -- NOTE this will need to be done if PYTHONPATH changes later
ENV PYTHONPATH=${NEMO_CHEM_HOME}:$PYTHONPATH
RUN NEMO_PATH=$(python -c 'import nemo; print(nemo.__path__[0])') && \
   cd ${NEMO_PATH}/collections/nlp/data/language_modeling/megatron && \
   make

WORKDIR ${NEMO_CHEM_HOME}
