FROM nvcr.io/nvidia/pytorch:21.10-py3

RUN apt update && rm -rf /var/lib/apt/lists/*

# Ensure apt-get won't prompt for selecting options
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    libsndfile1 sox \
    python-setuptools swig \
    python-dev ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# RUN pip install pytorch-lightning==1.5.0rc0 && \
# 	sed -i "s/from pytorch_lightning.callbacks.quantization import QuantizationAwareTraining/try:\\n\\tfrom pytorch_lightning.callbacks.quantization import QuantizationAwareTraining\\nexcept:\\n\\tpass/g" /opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py

# NVIDIA NeMo
ARG NEMO_BASE_HOME=/workspace/nemo_base
RUN git clone https://github.com/NVIDIA/NeMo.git ${NEMO_BASE_HOME} && \
	cd ${NEMO_BASE_HOME} && \
	git checkout 967256f5740fb0c324751090e16c78f2624e54d2 && \ 
	sh reinstall.sh

RUN pip install wandb==0.10.21