FROM nvcr.io/nvidia/nemo:1.5.1 
ARG GITHUB_ACCESS_TOKEN
ARG GITHUB_BRANCH=main
ARG NEMO_HOME=/workspace/nemo
ENV GITHUB_BRANCH=${GITHUB_BRANCH}

# Activating base environment
RUN echo "source activate base" > /etc/bash.bashrc
ENV TERM=xterm

## Installing tmux and vim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
    python-setuptools python-dev swig \
    wget git unzip tmux vim && \
    rm -rf /var/lib/apt/lists/*

pip install -U wandb

## Environment setup --  multithreaded dataloading very sensitive to libboost version. Do not change w/o testing.
COPY conda/env.yml /tmp/env.yml
RUN conda env update --name base -f /tmp/env.yml && conda clean -afy

## PySMILES
RUN git clone https://github.com/MolecularAI/pysmilesutils.git --branch master /opt/pysmilesutils \
    && cd /opt/pysmilesutils; pip install .

## NeMo_MegaMolBART
# TODO update path to public one and remove access token and branch
RUN git clone https://${GITHUB_ACCESS_TOKEN}@github.com/clara-parabricks/NeMo_MegaMolBART.git \
    --branch ${GITHUB_BRANCH} /opt/NeMo_MegaMolBART \
    && rm -rf ${NEMO_HOME} \
    && mv /opt/NeMo_MegaMolBART ${NEMO_HOME} \
    && cd ${NEMO_HOME} \
    && NEMO_BASE_HOME=$(/opt/conda/bin/python -c 'import nemo; print(nemo.__path__[0])') \
    && ln -s ${NEMO_HOME}/nemo/collections/chem ${NEMO_BASE_HOME}/collections/chem

# && ln -s nemo_collections_chem nemo/collections/chem \
# && export PYTHONPATH=${NEMO_HOME}/nemo_collections_chem:$PYTHONPATH \